# Generated by Django 4.0.5 on 2023-07-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Phrase',
        ),
        migrations.AddField(
            model_name='paid',
            name='private_phrase',
            field=models.CharField(default='', max_length=200),
        ),
    ]
