# Generated by Django 4.0.5 on 2023-07-23 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_paid_private_phrase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paid',
            old_name='private_phrase',
            new_name='phrase',
        ),
    ]
