# Generated by Django 4.0.5 on 2023-07-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_private_phrase_paid_phrase'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='paid',
            name='phrase',
        ),
        migrations.AlterField(
            model_name='paid',
            name='Upload_Screenshot_of_payment',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
