# Generated by Django 4.0.5 on 2023-07-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_phrase_remove_paid_phrase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid',
            name='Upload_Screenshot_of_payment',
            field=models.ImageField(blank=True, upload_to='images/upload/'),
        ),
    ]
