# Generated by Django 4.0.5 on 2023-07-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_paid_upload_screenshot_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid',
            name='Upload_Screenshot_of_payment',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
