# Generated by Django 4.0.5 on 2023-07-24 06:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_paid_upload_screenshot_of_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid',
            name='Upload_Screenshot_of_payment',
            field=cloudinary.models.CloudinaryField(default='', max_length=255, verbose_name='image'),
        ),
    ]
